### ISSUE TITLE
Clean installation: Internal Server Error

### ISSUE THREAD

**Issue by fly-man-** [mwozniak/bookmark-manager#3]
PDO: Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'bookmarks.cats.tok' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

• /home/bookmarks/public_html/lib/db/sql/mapper.php:202 DB\SQL->exec(array('SELECT \* FROM `catgroup`;'),array(array()),0)
• /home/bookmarks/public_html/lib/db/sql/mapper.php:240 DB\SQL\Mapper->select('*',NULL,array('group'=>NULL,'order'=>NULL,'limit'=>0,'offset'=>0),0)
• /home/bookmarks/public_html/lib/db/cursor.php:105 DB\SQL\Mapper->find(NULL,array('group'=>NULL,'order'=>NULL,'limit'=>0,'offset'=>0))
• /home/bookmarks/public_html/app/models/CatGroup.php:10 DB\Cursor->load()
• /home/bookmarks/public_html/app/controllers/Controller.php:22 CatGroup->all()
• /home/bookmarks/public_html/index.php:9 Base->run()

This is when the database is setup clean, any ideas how to fix this ?

**Comment by christianbur** [comment]
use this views

CREATE VIEW catgroup AS
    SELECT
        cats.name AS cat,
        cats.tok AS tok,
        cats.url AS url,
        count(*) AS itemcount
    FROM cats
    JOIN items ON
        items.cid=cats.tok
    GROUP BY
         cats.name, cats.tok, cats.url
    ORDER BY itemcount DESC;

CREATE VIEW taglist AS
    SELECT
        tags.label,
        tags.tok, 
        tags.url, 
        items.tok as itok,
        items.cid as ctok
    FROM tags
    JOIN tag2item ON 
         tag2item.tid = tags.id
    JOIN items ON 
          tag2item.iid = items.id
    ORDER BY tags.label, tags.tok, tags. url, items.tok, items.cid;

CREATE VIEW taggroup AS
    SELECT
        tags.label AS tag,
        tags.tok AS tok,
        tags.url AS url,
        count(*) AS tagcount
    FROM tags
    JOIN tag2item ON
        tag2item.tid = tags.id
    GROUP BY
    tags.label, tags.tok, tags.url
    ORDER BY tagcount DESC;
